services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: taskmgr_api
    environment:
      # tighten this to only the web container’s public URL(s)
      - CORS_ALLOW_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ui/Dockerfile
      args:
        # UI will call API inside the Docker network as http://api:8000
        - VITE_API_BASE_URL=http://api:8000
    container_name: taskmgr_web
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  default:
    name: taskmgr_net
